# Generated by Django 3.2.7 on 2021-09-18 17:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KR', unique=True)),
            ],
            options={
                'verbose_name_plural': 'churches',
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('memo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'cohorts',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cohort')),
            ],
            options={
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RoleGroupJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'titles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KR', unique=True)),
                ('memo', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cohort')),
                ('rolegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rolegroupjoin')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.title')),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
    ]
