# Generated by Django 3.2.7 on 2021-09-18 15:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KR', unique=True)),
            ],
            options={
                'verbose_name_plural': 'churches',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KR', unique=True)),
                ('memo', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
    ]
