# Generated by Django 3.2.7 on 2021-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('contact', models.IntegerField()),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
