# Generated by Django 3.2.7 on 2021-09-18 16:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_church_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KR', unique=True),
        ),
    ]
