# Generated by Django 3.2.7 on 2021-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_church_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='memo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
