# Generated by Django 3.2.7 on 2021-09-13 13:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KR', unique=True),
        ),
    ]
