# Generated by Django 3.2.7 on 2021-09-18 14:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KR', unique=True)),
            ],
        ),
    ]
